package com.myschoolprj.employeems.UI;

import com.myschoolprj.employeems.utils.GradientPanels;
import com.myschoolprj.employeems.dao.AdminDAO;
import com.myschoolprj.employeems.model.Admin;
import com.myschoolprj.employeems.utils.PlaceholderUtils;
import com.myschoolprj.employeems.utils.Validator;

import java.awt.CardLayout;
import java.sql.SQLException;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

public class LoginForm extends javax.swing.JFrame {

    public LoginForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lfLeftPanel = new GradientPanels(Color.decode("#272b3f"), Color.decode("#256b51"));
        lfLeftTitle = new javax.swing.JLabel();
        lfLeftIcon = new javax.swing.JLabel();
        lfRightPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lfRightTitle2 = new javax.swing.JLabel();
        usernameTF = new javax.swing.JTextField();
        passwordTF = new javax.swing.JPasswordField();
        loginBtn = new javax.swing.JButton();
        showPassCB = new javax.swing.JCheckBox();
        closeBtn = new javax.swing.JButton();
        switchToRegBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lfRightTitle1 = new javax.swing.JLabel();
        regUsernameTF = new javax.swing.JTextField();
        regPasswordTF = new javax.swing.JPasswordField();
        registerBtn = new javax.swing.JButton();
        showBothPassCB = new javax.swing.JCheckBox();
        regCloseBtn = new javax.swing.JButton();
        regConPasswordTF = new javax.swing.JPasswordField();
        switchToLogBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(712, 460));
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        lfLeftPanel.setPreferredSize(new java.awt.Dimension(356, 500));

        lfLeftTitle.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lfLeftTitle.setForeground(new java.awt.Color(255, 255, 255));
        lfLeftTitle.setText("Employee Management System");

        lfLeftIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/multiple-users-silhouette.png"))); // NOI18N

        javax.swing.GroupLayout lfLeftPanelLayout = new javax.swing.GroupLayout(lfLeftPanel);
        lfLeftPanel.setLayout(lfLeftPanelLayout);
        lfLeftPanelLayout.setHorizontalGroup(
            lfLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lfLeftPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(lfLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lfLeftPanelLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(lfLeftIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lfLeftTitle, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        lfLeftPanelLayout.setVerticalGroup(
            lfLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lfLeftPanelLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(lfLeftIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lfLeftTitle)
                .addContainerGap(232, Short.MAX_VALUE))
        );

        getContentPane().add(lfLeftPanel);

        lfRightPanel.setLayout(new java.awt.CardLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        lfRightTitle2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lfRightTitle2.setForeground(new java.awt.Color(37, 103, 81));
        lfRightTitle2.setText("Welcome back Admin!");

        usernameTF.setForeground(new java.awt.Color(153, 153, 153));
        usernameTF.setText("Enter Username");
        usernameTF.setPreferredSize(new java.awt.Dimension(200, 40));
        usernameTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameTFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameTFFocusLost(evt);
            }
        });

        passwordTF.setForeground(new java.awt.Color(153, 153, 153));
        passwordTF.setText("Enter Password");
        passwordTF.setEchoChar('\u0000');
        passwordTF.setPreferredSize(new java.awt.Dimension(200, 40));
        passwordTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordTFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordTFFocusLost(evt);
            }
        });
        passwordTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passwordTFKeyTyped(evt);
            }
        });

        loginBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        loginBtn.setText("Login");
        loginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBtn.setPreferredSize(new java.awt.Dimension(240, 40));
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        showPassCB.setText("Show Password");
        showPassCB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showPassCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPassCBActionPerformed(evt);
            }
        });

        closeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-x-24.png"))); // NOI18N
        closeBtn.setBorder(null);
        closeBtn.setBorderPainted(false);
        closeBtn.setContentAreaFilled(false);
        closeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeBtn.setFocusPainted(false);
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });

        switchToRegBtn.setBorderPainted(false);
        switchToRegBtn.setContentAreaFilled(false);
        switchToRegBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        switchToRegBtn.setLabel("No account? Sign up");
        switchToRegBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                switchToRegBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                switchToRegBtnMouseExited(evt);
            }
        });
        switchToRegBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchToRegBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lfRightTitle2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(closeBtn))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(passwordTF, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(usernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(switchToRegBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(showPassCB)))
                        .addGap(0, 38, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(closeBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(lfRightTitle2)
                .addGap(34, 34, 34)
                .addComponent(usernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passwordTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(switchToRegBtn)
                    .addComponent(showPassCB))
                .addGap(54, 54, 54)
                .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        lfRightPanel.add(jPanel3, "Login card");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lfRightTitle1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lfRightTitle1.setForeground(new java.awt.Color(37, 103, 81));
        lfRightTitle1.setText("Register");
        lfRightTitle1.setToolTipText("");

        regUsernameTF.setForeground(new java.awt.Color(153, 153, 153));
        regUsernameTF.setText("Enter Username");
        regUsernameTF.setPreferredSize(new java.awt.Dimension(200, 40));
        regUsernameTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                regUsernameTFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                regUsernameTFFocusLost(evt);
            }
        });

        regPasswordTF.setForeground(new java.awt.Color(153, 153, 153));
        regPasswordTF.setText("Enter Password");
        regPasswordTF.setEchoChar('\u0000');
        regPasswordTF.setPreferredSize(new java.awt.Dimension(240, 40));
        regPasswordTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                regPasswordTFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                regPasswordTFFocusLost(evt);
            }
        });
        regPasswordTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                regPasswordTFKeyTyped(evt);
            }
        });

        registerBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        registerBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerBtn.setLabel("Sign up");
        registerBtn.setPreferredSize(new java.awt.Dimension(240, 40));
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });

        showBothPassCB.setText("Show Password");
        showBothPassCB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showBothPassCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showBothPassCBActionPerformed(evt);
            }
        });

        regCloseBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-x-24.png"))); // NOI18N
        regCloseBtn.setBorder(null);
        regCloseBtn.setBorderPainted(false);
        regCloseBtn.setContentAreaFilled(false);
        regCloseBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        regCloseBtn.setFocusPainted(false);
        regCloseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regCloseBtnActionPerformed(evt);
            }
        });

        regConPasswordTF.setForeground(new java.awt.Color(153, 153, 153));
        regConPasswordTF.setText("Confirm Password");
        regConPasswordTF.setEchoChar('\u0000');
        regConPasswordTF.setPreferredSize(new java.awt.Dimension(240, 40));
        regConPasswordTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                regConPasswordTFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                regConPasswordTFFocusLost(evt);
            }
        });
        regConPasswordTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                regConPasswordTFKeyTyped(evt);
            }
        });

        switchToLogBtn.setBorderPainted(false);
        switchToLogBtn.setContentAreaFilled(false);
        switchToLogBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        switchToLogBtn.setLabel("Have account? Login");
        switchToLogBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                switchToLogBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                switchToLogBtnMouseExited(evt);
            }
        });
        switchToLogBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchToLogBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(326, Short.MAX_VALUE)
                .addComponent(regCloseBtn)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lfRightTitle1)
                        .addGap(71, 71, 71))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(regUsernameTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(regPasswordTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(regConPasswordTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(switchToLogBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(showBothPassCB))
                    .addComponent(registerBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(regCloseBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(lfRightTitle1)
                .addGap(44, 44, 44)
                .addComponent(regUsernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(regPasswordTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(regConPasswordTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showBothPassCB)
                    .addComponent(switchToLogBtn))
                .addGap(57, 57, 57)
                .addComponent(registerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        lfRightPanel.add(jPanel2, "Register card");

        getContentPane().add(lfRightPanel);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        this.requestFocusInWindow();
    }//GEN-LAST:event_formWindowGainedFocus

    private void regUsernameTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regUsernameTFFocusGained
        PlaceholderUtils.handleFocusedPlaceholder(regUsernameTF, "Enter Username");
    }//GEN-LAST:event_regUsernameTFFocusGained

    private void regUsernameTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regUsernameTFFocusLost
        PlaceholderUtils.handleFocusedPlaceholder(regUsernameTF, "Enter Username");
    }//GEN-LAST:event_regUsernameTFFocusLost

    private void regPasswordTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regPasswordTFFocusGained
        PlaceholderUtils.handleFocusedPlaceholder(regPasswordTF, "Enter Password");
    }//GEN-LAST:event_regPasswordTFFocusGained

    private void regPasswordTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regPasswordTFFocusLost
        PlaceholderUtils.handleFocusedPlaceholder(regPasswordTF, "Enter Password");
    }//GEN-LAST:event_regPasswordTFFocusLost

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        // read  messages
        StringBuilder sb = new StringBuilder();

        // check empty fields and special characters
        boolean filledUsername = Validator.checkSpecialCharacters(regUsernameTF, sb, "Username can't be blank");
        boolean filledPassword = Validator.checkSpecialCharacters(regPasswordTF, sb, "Password can't be blank");
        boolean filledConPassword = Validator.checkEmptyFields(regConPasswordTF, sb, "Please fill confirmed password too!");

        // checked values equal false
        if (!filledUsername || !filledPassword || !filledConPassword) {
            JOptionPane.showMessageDialog(this, sb.toString(), "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        // true -> get field's values
        String username = regUsernameTF.getText().trim();
        String password = regPasswordTF.getText();
        String confirmedPassword = regConPasswordTF.getText();

        // check identical passwords
        if (!password.equals(confirmedPassword)) {
            JOptionPane.showMessageDialog(this, "Confirmed password did not match with password", "Input error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // regsiter event handler
        try {
            // create "AdminDAO" instance to handle database interactivities
            AdminDAO adDAO = new AdminDAO();

            // check whether the returned admin is null
            if (adDAO.existedUsername(username)) {
                // check duplicate username (don't allow identical username)
                JOptionPane.showMessageDialog(this, "Username has existed, please enter a different one", "Input error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            // create admin credential and save into db
            adDAO.createAdminCredentials(username, password);
            JOptionPane.showMessageDialog(this, "Account created successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            // show login layout after accomplishing creating
            CardLayout cl = (CardLayout) lfRightPanel.getLayout();
            cl.show(lfRightPanel, "Login card");

            // error catchers
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "There was an issue with the database operation. Please try again.", "Database Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "An unexpected error occurred: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_registerBtnActionPerformed

    private void showBothPassCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showBothPassCBActionPerformed
        if (showBothPassCB.isSelected()) {
            regPasswordTF.setEchoChar('\u0000');
            regConPasswordTF.setEchoChar('\u0000');
        } else {
            regPasswordTF.setEchoChar('*');
            regConPasswordTF.setEchoChar('*');
        }
    }//GEN-LAST:event_showBothPassCBActionPerformed

    private void regCloseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regCloseBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_regCloseBtnActionPerformed

    private void regConPasswordTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regConPasswordTFFocusGained
        PlaceholderUtils.handleFocusedPlaceholder(regConPasswordTF, "Confirm Password");
    }//GEN-LAST:event_regConPasswordTFFocusGained

    private void regConPasswordTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regConPasswordTFFocusLost
        PlaceholderUtils.handleFocusedPlaceholder(regConPasswordTF, "Confirm Password");
    }//GEN-LAST:event_regConPasswordTFFocusLost

    private void usernameTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameTFFocusGained
        PlaceholderUtils.handleFocusedPlaceholder(usernameTF, "Enter Username");
    }//GEN-LAST:event_usernameTFFocusGained

    private void usernameTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameTFFocusLost
        PlaceholderUtils.handleFocusedPlaceholder(usernameTF, "Enter Username");
    }//GEN-LAST:event_usernameTFFocusLost

    private void passwordTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordTFFocusGained
        PlaceholderUtils.handleFocusedPlaceholder(passwordTF, "Enter Password");
    }//GEN-LAST:event_passwordTFFocusGained

    private void passwordTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordTFFocusLost
        PlaceholderUtils.handleFocusedPlaceholder(passwordTF, "Enter Password");
    }//GEN-LAST:event_passwordTFFocusLost

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // read messages
        StringBuilder sb = new StringBuilder();

        // check empty fields and special characters
        boolean filledUsername = Validator.checkSpecialCharacters(usernameTF, sb, "Username can't be blank");
        boolean filledUPassword = Validator.checkSpecialCharacters(passwordTF, sb, "Password can't be blank");

        if (!filledUsername || !filledUPassword) {
            JOptionPane.showMessageDialog(this, sb.toString(), "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String username = usernameTF.getText().trim();
        String password = passwordTF.getText().trim();

        try {
            // Create an instance of AdminDAO
            AdminDAO adminDAO = new AdminDAO();
            // Get the matching Admin object
            Admin admin = adminDAO.getAdminByCredentials(username, password);

            if (admin != null) {
                JOptionPane.showMessageDialog(this, "Login successful! Welcome " + admin.getName(), "Success", JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
                MainForm mf = new MainForm();
                mf.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Invalid username or password.", "Login Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "There was an issue with the database operation. Please try again.", "Database Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "An unexpected error occurred: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeBtnActionPerformed

    private void switchToRegBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_switchToRegBtnMouseEntered
        switchToRegBtn.setForeground(Color.decode("#256b51"));
    }//GEN-LAST:event_switchToRegBtnMouseEntered

    private void switchToRegBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_switchToRegBtnMouseExited
        switchToRegBtn.setForeground(Color.BLACK);
    }//GEN-LAST:event_switchToRegBtnMouseExited

    private void showPassCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPassCBActionPerformed
        if (showPassCB.isSelected()) {
            passwordTF.setEchoChar('\u0000');
        } else {
            passwordTF.setEchoChar('*');
        }
    }//GEN-LAST:event_showPassCBActionPerformed

    private void switchToRegBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switchToRegBtnActionPerformed
        CardLayout cl = (CardLayout) lfRightPanel.getLayout();
        cl.show(lfRightPanel, "Register card");
    }//GEN-LAST:event_switchToRegBtnActionPerformed

    private void switchToLogBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switchToLogBtnActionPerformed
        CardLayout cl = (CardLayout) lfRightPanel.getLayout();
        cl.show(lfRightPanel, "Login card");
    }//GEN-LAST:event_switchToLogBtnActionPerformed

    private void switchToLogBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_switchToLogBtnMouseEntered
        switchToLogBtn.setForeground(Color.decode("#256b51"));
    }//GEN-LAST:event_switchToLogBtnMouseEntered

    private void switchToLogBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_switchToLogBtnMouseExited
        switchToLogBtn.setForeground(Color.BLACK);
    }//GEN-LAST:event_switchToLogBtnMouseExited

    private void regPasswordTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_regPasswordTFKeyTyped
        checkPasswordSpaces(regPasswordTF, evt);
    }//GEN-LAST:event_regPasswordTFKeyTyped

    private void regConPasswordTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_regConPasswordTFKeyTyped
        checkPasswordSpaces(regConPasswordTF, evt);
    }//GEN-LAST:event_regConPasswordTFKeyTyped

    private void passwordTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordTFKeyTyped
        checkPasswordSpaces(passwordTF, evt);
    }//GEN-LAST:event_passwordTFKeyTyped

    private void checkPasswordSpaces(JTextField tf, java.awt.event.KeyEvent evt) {
        char keyChar = evt.getKeyChar();

        if (keyChar == java.awt.event.KeyEvent.VK_SPACE) {
            JOptionPane.showMessageDialog(this, "Spaces are not allowed within password.", "Input Error", JOptionPane.ERROR_MESSAGE);
            // Consume the event to prevent the space from being typed into the field
            evt.consume();
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeBtn;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lfLeftIcon;
    private javax.swing.JPanel lfLeftPanel;
    private javax.swing.JLabel lfLeftTitle;
    private javax.swing.JPanel lfRightPanel;
    private javax.swing.JLabel lfRightTitle1;
    private javax.swing.JLabel lfRightTitle2;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPasswordField passwordTF;
    private javax.swing.JButton regCloseBtn;
    private javax.swing.JPasswordField regConPasswordTF;
    private javax.swing.JPasswordField regPasswordTF;
    private javax.swing.JTextField regUsernameTF;
    private javax.swing.JButton registerBtn;
    private javax.swing.JCheckBox showBothPassCB;
    private javax.swing.JCheckBox showPassCB;
    private javax.swing.JButton switchToLogBtn;
    private javax.swing.JButton switchToRegBtn;
    private javax.swing.JTextField usernameTF;
    // End of variables declaration//GEN-END:variables
}
